stages:
  - test
  - run

variables:
  SHEET_TITLE: "Диски"
  TITLE_ROWS_COUNT: "1"
  URL_COL_NUM: "2"
  PRICE_COL_LTR: "F"

pre-commit:
  stage: .pre
  extends: .base
  cache:
    key:
      files:
        - .pre-commit-config.yaml
      prefix: $CI_JOB_NAME
    paths:
      - ${PRE_COMMIT_HOME}
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  script:
    - apt-get update && apt-get install -y --no-install-recommends git
    - pip install --no-cache-dir --upgrade pre-commit
    - pre-commit run --all-files --show-diff-on-failure --verbose --color always
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: on_success

test:
  stage: test
  extends: .base
  cache:
    key: test
    paths:
      - venv/
  script:
    - pip install --no-cache-dir --upgrade -r requirements.dev.txt
    - pytest --cov-report xml:reports/coverage.xml --junitxml=reports/pytest.xml -v
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: on_success
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      junit: reports/pytest.xml
      coverage_report:
        coverage_format: cobertura
        path: reports/coverage.xml

run:
  stage: run
  extends: .base
  cache:
    key: run
    paths:
      - venv/
  script:
    - pip install --no-cache-dir --upgrade -r requirements.txt
    - playwright install firefox
    - cp $GOOGLE_SA_KEYFILE price_ru/cred.json
    - python -m price_ru
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: manual
  retry: 1

.base:
  image: ghcr.io/spirkaa/python:3.11-bullseye-playwright-firefox
  before_script:
    - python --version
    - python -m venv venv
    - source venv/bin/activate
