image: ghcr.io/spirkaa/python:3.11-bullseye-playwright-firefox

variables:
  # PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  SHEET_TITLE: "Диски"
  TITLE_ROWS_COUNT: "1"
  URL_COL_NUM: "2"
  PRICE_COL_LTR: "F"

cache:
  paths:
    # - .cache/pip
    - venv/

before_script:
  - python --version
  - python -m venv venv
  - source venv/bin/activate
  - pip install --no-cache-dir --upgrade -r requirements.txt
  - playwright install firefox

run:
  script:
    - cp $GOOGLE_SA_KEYFILE price_ru/cred.json
    - python -m price_ru
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - when: manual
