[tool.pytest.ini_options]
addopts = "--cov=. --cov-report term-missing:skip-covered"

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_also = [
  "if __name__ == .__main__.:",
]

[tool.ruff]
ignore = [
  "E203", # whitespace before ':'
  "E501", # line length violations
]
select = [
  "E", # pycodestyle errors
  "W", # pycodestyle warnings
  "F", # pyflakes
  "B", # flake8-bugbear
  "C4", # flake8-comprehensions
  "I", # isort
  "UP", # pyupgrade
  "FBT", # flake8-boolean-trap
  "PIE", # flake8-pie
  "SIM", # flake8-simplify
  "PT", # flake8-pytest-style
  "RET", # flake8-return
  "PTH", # flake8-use-pathlib
  "S", # flake8-bandit
]
target-version = "py311"

[tool.ruff.per-file-ignores]
"*test*" = ["S101"] # allow assert statements in test cases

[tool.ruff.isort]
combine-as-imports = true
